# This is a basic workflow to help you get started with Actions

name: Add the Overdue On date to project items

# Controls when the workflow will run
on:
  #schedule:
  #  - cron: '* * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-overdue-dates-on-squad-work:
    name: Update squad work project items with an overdue date
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@master
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TN_PAT }}
          script: |
            const script = require('.github/scripts/overdue-date-automation.js');
            (async () => {
              await script({github, context});
            })();