# This is a basic workflow to help you get started with Actions

name: Add the Overdue On date to issues

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-status:
    name: Check status on issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TN_PAT }}
          script: |
            const query = `query($owner:String!, $projectNum:Int!) {
              user(login:$owner) { 
                projectV2(number:$projectNum) { 
                  items(first: 100) {
                    nodes { 
                      id
                      fields(first: 100){
                        nodes {
                          ... on ProjectV2Field {
                            name
                            id
                          } 
                        }
                      }
                      fieldValues(first: 100) {
                        nodes {
                          ... on ProjectV2ItemFieldTextValue {
                            text
                            id
                            updatedAt
                            createdAt
                            creator {
                              url
                            }
                          }
                          ... on ProjectV2ItemFieldSingleSelectValue {
                            field {
                              ... on ProjectV2SingleSelectField {
                                name
                              }
                            }
                            name
                            id
                          }
                          ... on ProjectV2ItemFieldDateValue { 
                            field {
                              ... on ProjectV2Field {
                                name
                              }
                            }
                            date
                          }
                        }
                      }  
                    } 
                  } 
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              projectNum: 170,
            }
            const result = await github.graphql(query, variables)
            console.log("result: " + result)

            var OverdueOnDate = ''
            var projectId = ''
            var itemId = ''
            var fieldId = ''
            var isSquadWork = false
            var isOverdueOnSet = false
            var createdAt = ''
            var overdueOnFieldId = ''
            
            for (const projectItem of result.user.projectV2.items.nodes){
              for (const fieldValue of projectItem.fieldValues.nodes) {
                if (fieldValue.field !== undefined){
                  if (fieldValue.field.name === 'Status'){
                    if (fieldValue.name === 'Squad Work'){                      
                      isSquadWork = true
                    }
                  } 
                  if (fieldValue.name === 'Overdue On'){
                    isOverdueOnSet = true
                  }
                } else {
                  createdAt = fieldValue.createdAt
                }
              }
              if (isSquadWork && !isOverdueOnSet){
                var createdAtString = createdAt
                var createdAtDateTime = new Date(createdAtString)
                var createdAtDateString = createdAtDateTime.toISOString().split('T')[0]
                var OverdueOnDate = new Date(createAtDateString)
                OverdueOnDate.setDate(OverdueOnDate.getDate() + 10)

                console.log('New OverdueOn: ' + OverdueOnDate.toISOString())
                
                projectId = result.user.projectV2.id
                console.log('Project ID: ' + projectId)
                itemId = projectItem.id
                console.log('Item ID: ' + itemId)
                overdueOnFieldId = getProjectv2FieldId("Overdue On")
                console.log('Overdue On Field ID: ' + overdueOnFieldId)
                updateOverdueOnDate(projectId, itemId, overdueOnFieldId, OverdueOnDate)
              }
            }
            

            function updateOverdueOnDate(projectId, itemId, fieldId, value){
              const mutation = `mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $value: Date!){
                updateProjectV2ItemFieldValue(input: {
                  projectId: $projectId
                  itemId: $itemId
                  fieldId: $fieldId
                  value: {date: $value}
                }){
                  projectV2Item {
                    id
                  }
                }
              }`;

              const result = await github.graphql(query, variables)
              console.log("result: " + result.projectV2Item.id)
            }

            function getProjectv2FieldId(name) {
              for (const field of result.user.projectV2.fields.nodes){
                if (field.name === name){
                  overdueOnFieldId = field.id
                  return overdueOnFieldId
                }
              }
            }
            
            
            //for (const node of result.repository.issues.nodes) {
            //  console.log("Node Id: " + node.id)
            //}
            //console.log(result)
            //const currentDateTime = new Date();
            //console.log('Current DateTime:', currentDateTime.toISOString());
