# This is a basic workflow to help you get started with Actions

name: Perform archive validation and execution on closed project item

# Controls when the workflow will run
on:
  #schedule:
  #  - cron: '* * * * *'

  issues:
    types:
      - closed
  pull_request:
    types:
      - closed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  archive-done-project-items:
    name: Archive project items that are done and don't need review from the squad
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@master
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TN_PAT }}
          script: |
            const script = require('.github/scripts/archive-done-items.js');
            (async () => {
              await script({github, context});
            })();