# This is a basic workflow to help you get started with Actions

name: Change a custom feild in an issue

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-status:
    name: Check status on issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const query = `query($owner:String!, $name:String!) {
              repository(owner:$owner, name:$name){
                issues(first:100) {
                  nodes {
                    id
                  }
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo,
            }
            const result = await github.graphql(query, variables)
            for (const node of result.repository.issues.nodes) {
              if (node.id === "I_kwDOJJR3y85rgpbs" ){
                console.log("Node Id: " + node.id)
              }
            }
            console.log(result)
