name: Mocha Tests

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install mocha@latest

      - name: Run Mocha tests
        run: npx mocha .github/scripts/tests/github-graphql-api-tests.js
        env:
          GITHUB_TOKEN: ${{ secrets.TN_PAT }}
