name: Mocha Tests

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '20'

      #- name: Install @actions/core
      #  run: npm install @actions/core

      #- name: Install @octokit/auth-token
      #  run: npm install @octokit/auth-token

      - name: Install mocha@latest
        run: npm install mocha@latest

      - name: Install chai@latest
        run: npm install chai@latest

      - name: Install nock@lastest
        run: npm install nock@latest
      
      - name: Install graphql@latest
        run: npm install graphql@latest

      - name: Install @actions/github
        run: npm install @actions/github

      - name: Install @octokit/rest
        run: npm install @octokit/rest

      - name: Run Mocha tests
        env:
          TN_PAT: ${{ secrets.TN_PAT }}
        run: npx mocha .github/scripts/tests/github-graphql-api-tests.mjs