name: Move issues opened or reopened to the corresponding column
on:
  issues:
    types: [opened, reopened]

env:
  not_scored: Not Scored

jobs:
  add-to-not-scored-column:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'issues' && !contains(github.event.issue.labels.*.name, 'Rotation-group tasks') && (github.event.action == 'opened' || github.event.action == 'reopened') }}
    steps:
      - name: Add issue to project
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          project_id: 165
          gh_token: ${{ secrets.TN_PAT }}
          organization: Particular
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.not_scored }}
